### ISSUE TITLE
reflect: call of reflect.Value.Interface on zero Value

### ISSUE THREAD

**Issue by tuananh** [acorn-io/baaah#18]
i tried the traefik publisher (https://github.com/acorn-io/traefik-hub-publisher) and play around with it a bit by changing to watching `corev1.Secret`, then i got error

`reflect: call of reflect.Value.Interface on zero Value)`

```go
router.Type(&corev1.Secret{}).Selector(sel).HandlerFunc(MyDummyHandler)

func MyDummyHandler(req router.Request, resp router.Response) error {
	return nil
}
```

i tried with other kind like Deployment or Ingress and it works fine.

the stacktrace is below

```
2022/06/29 17:49:19 INFO: Starting /v1, Kind=Secret controller
INFO[0000] Handling kube-system/bootstrap-token-abcdef /v1, Kind=Secret 
E0629 17:49:19.458016   33390 runtime.go:79] Observed a panic: &reflect.ValueError{Method:"reflect.Value.Interface", Kind:0x0} (reflect: call of reflect.Value.Interface on zero Value)
goroutine 373 [running]:
k8s.io/apimachinery/pkg/util/runtime.logPanic({0x101cfd4e0?, 0x140000a9950})
        /Users/anhtran/go/pkg/mod/k8s.io/apimachinery@v0.24.2/pkg/util/runtime/runtime.go:75 +0x7c
k8s.io/apimachinery/pkg/util/runtime.HandleCrash({0x0, 0x0, 0x140003ae120?})
        /Users/anhtran/go/pkg/mod/k8s.io/apimachinery@v0.24.2/pkg/util/runtime/runtime.go:49 +0x7c
panic({0x101cfd4e0, 0x140000a9950})
        /usr/local/go/src/runtime/panic.go:838 +0x204
reflect.valueInterface({0x0?, 0x0?, 0x1400083b468?}, 0x35?)
        /usr/local/go/src/reflect/value.go:1435 +0x100
reflect.Value.Interface(...)
        /usr/local/go/src/reflect/value.go:1430
github.com/acorn-io/baaah/pkg/router.statusField({0x101e9fe88?, 0x140006ce000?})
        /Users/anhtran/go/pkg/mod/github.com/acorn-io/baaah@v0.0.0-20220628235037-fa94a0793854/pkg/router/save.go:49 +0xf8
github.com/acorn-io/baaah/pkg/router.statusChanged({0x101e9fe88?, 0x140006ce000?}, {0x101e9fe88, 0x1400013eb40})
        /Users/anhtran/go/pkg/mod/github.com/acorn-io/baaah@v0.0.0-20220628235037-fa94a0793854/pkg/router/save.go:53 +0x30
github.com/acorn-io/baaah/pkg/router.(*save).save(0x140005e67b0, {0x101e9fe88, 0x140006ce000}, {{0x101eb0dc8, 0x1400070e000}, {0x101eb45a0, 0x1400013eb40}, {0x101eae1d0, 0x1400070db40}, {{0x0, ...}, ...}, ...}, ...)
        /Users/anhtran/go/pkg/mod/github.com/acorn-io/baaah@v0.0.0-20220628235037-fa94a0793854/pkg/router/save.go:40 +0x144
github.com/acorn-io/baaah/pkg/router.(*HandlerSet).handle(0x140005e6700, {{0x0, 0x0}, {0x101a0ae75, 0x2}, {0x101c257be, 0x6}}, {0x140003c0150?, 0x1400084aa38?}, {0x101e9fe88, ...}, ...)
        /Users/anhtran/go/pkg/mod/github.com/acorn-io/baaah@v0.0.0-20220628235037-fa94a0793854/pkg/router/handler.go:229 +0x594
github.com/acorn-io/baaah/pkg/router.(*HandlerSet).onChange(0x140005e6700, {{0x0, 0x0}, {0x101a0ae75, 0x2}, {0x101c257be, 0x6}}, {0x140003c0150, 0x22}, {0x101e9fe88, ...})
        /Users/anhtran/go/pkg/mod/github.com/acorn-io/baaah@v0.0.0-20220628235037-fa94a0793854/pkg/router/handler.go:199 +0x268
github.com/acorn-io/baaah/pkg/lasso.(*Backend).Watch.func1({0x140003c0150?, 0x62bc2e2f?}, {0x101e9fe88?, 0x140006ce000?})
        /Users/anhtran/go/pkg/mod/github.com/acorn-io/baaah@v0.0.0-20220628235037-fa94a0793854/pkg/lasso/backend.go:64 +0x70
github.com/rancher/lasso/pkg/controller.SharedControllerHandlerFunc.OnChange(0x14000073438?, {0x140003c0150?, 0x140000733a8?}, {0x101e9fe88?, 0x140006ce000?})
        /Users/anhtran/go/pkg/mod/github.com/rancher/lasso@v0.0.0-20220628160937-749b3397db38/pkg/controller/sharedcontroller.go:29 +0x44
github.com/rancher/lasso/pkg/controller.(*SharedHandler).OnChange(0x14000888730, {0x140003c0150, 0x22}, {0x101e9fe88, 0x140006ce000})
        /Users/anhtran/go/pkg/mod/github.com/rancher/lasso@v0.0.0-20220628160937-749b3397db38/pkg/controller/sharedhandler.go:75 +0x240
github.com/rancher/lasso/pkg/controller.(*controller).syncHandler(0x1400043a000, {0x140003c0150, 0x22})
        /Users/anhtran/go/pkg/mod/github.com/rancher/lasso@v0.0.0-20220628160937-749b3397db38/pkg/controller/controller.go:233 +0xa0
github.com/rancher/lasso/pkg/controller.(*controller).processSingleItem(0x1400043a000, {0x101cc3ec0?, 0x140003ae120?})
        /Users/anhtran/go/pkg/mod/github.com/rancher/lasso@v0.0.0-20220628160937-749b3397db38/pkg/controller/controller.go:214 +0xbc
github.com/rancher/lasso/pkg/controller.(*controller).processNextWorkItem(0x1400043a000)
        /Users/anhtran/go/pkg/mod/github.com/rancher/lasso@v0.0.0-20220628160937-749b3397db38/pkg/controller/controller.go:191 +0x48
github.com/rancher/lasso/pkg/controller.(*controller).runWorker(0x14000073688?)
        /Users/anhtran/go/pkg/mod/github.com/rancher/lasso@v0.0.0-20220628160937-749b3397db38/pkg/controller/controller.go:180 +0x2c
k8s.io/apimachinery/pkg/util/wait.BackoffUntil.func1(0x36b8?)
        /Users/anhtran/go/pkg/mod/k8s.io/apimachinery@v0.24.2/pkg/util/wait/wait.go:155 +0x44
k8s.io/apimachinery/pkg/util/wait.BackoffUntil(0x6?, {0x101e9bc98, 0x1400071b1a0}, 0x1, 0x140004ea120)
        /Users/anhtran/go/pkg/mod/k8s.io/apimachinery@v0.24.2/pkg/util/wait/wait.go:156 +0x94
k8s.io/apimachinery/pkg/util/wait.JitterUntil(0x140008b6300?, 0x3b9aca00, 0x0, 0x90?, 0x0?)
        /Users/anhtran/go/pkg/mod/k8s.io/apimachinery@v0.24.2/pkg/util/wait/wait.go:133 +0x84
k8s.io/apimachinery/pkg/util/wait.Until(0x7?, 0x14000073770?, 0x101e96b78?)
        /Users/anhtran/go/pkg/mod/k8s.io/apimachinery@v0.24.2/pkg/util/wait/wait.go:90 +0x2c
created by github.com/rancher/lasso/pkg/controller.(*controller).run
        /Users/anhtran/go/pkg/mod/github.com/rancher/lasso@v0.0.0-20220628160937-749b3397db38/pkg/controller/controller.go:148 +0x2b8
panic: reflect: call of reflect.Value.Interface on zero Value [recovered]
        panic: reflect: call of reflect.Value.Interface on zero Value
```

**Comment by ibuildthecloud** [comment]
This should be fixed here https://github.com/acorn-io/baaah/commit/91ce7be33b5f8a279e76817597431d8ce40ad4a9#diff-f8de695a94d7d7f2b3bd23c2dc212d2b95cde271957ba146235104b7afa0ff40L49
